databases:
  - name: BudgetPro
    databaseName: BudgetPro
    user: BudgetPro

services:
  - type: web
    name: BudgetPro
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: BudgetPro
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false